
import { format } from 'date-fns';
import { CleaningTask, NewCleaningTask, CleaningStatus, CleaningPhoto } from '@/types/cleaning';

import photoSalon from '@/assets/cleaning/photo-salon.jpg';
import photoCuisine from '@/assets/cleaning/photo-cuisine.jpg';
import photoChambre from '@/assets/cleaning/photo-chambre.jpg';
import photoSdb from '@/assets/cleaning/photo-sdb.jpg';
import photoEntree from '@/assets/cleaning/photo-entree.jpg';
import photoChambre2 from '@/assets/cleaning/photo-chambre2.jpg';
import photoSdb2 from '@/assets/cleaning/photo-sdb2.jpg';
import photoCuisine2 from '@/assets/cleaning/photo-cuisine2.jpg';

// Initial sample cleaning tasks
export const initialTodayTasks: CleaningTask[] = [
  {
    id: 1,
    property: 'Coeur de Lyon - Stendhal',
    displayId: '#05',
    address: '50 Rue Mercière, 69002, Lyon',
    checkoutTime: '11:00',
    checkinTime: '15:00',
    checkoutDateLabel: 'ven. 26 juin',
    checkinDateLabel: 'mer. 24 juin',
    nights: 2,
    guests: 2,
    agency: 'Sihem',
    status: 'todo',
    cleaningAgent: 'Sihem',
    startTime: '',
    endTime: '',
    linens: ['Draps king size x1', 'Serviettes bain x2'],
    consumables: ['Capsules café x4', 'Gel douche x1'],
    comments: '',
    problems: [],
    isSameDayCheckin: true,
    assignedVia: 'auto',
  },
  {
    id: 2,
    property: "L'Annexe",
    displayId: '#09',
    address: '8 Rue Hippolyte Flandrin, 69001, Lyon',
    checkoutTime: '11:00',
    checkinTime: '16:00',
    checkoutDateLabel: 'ven. 26 juin',
    checkinDateLabel: 'dim. 21 juin',
    nights: 5,
    guests: 2,
    agency: 'Amel',
    status: 'todo',
    cleaningAgent: 'Amel',
    startTime: '',
    endTime: '',
    linens: ['Draps simple x1'],
    consumables: ['Capsules café x2'],
    comments: '',
    problems: [],
    isSameDayCheckin: true,
    assignedVia: 'auto',
  },
  {
    id: 3,
    property: 'La Meurice - Jardin',
    displayId: '#15',
    address: '70 Rue Maurice Flandin, 69003, Lyon',
    checkoutTime: '11:00',
    checkinTime: '15:00',
    checkoutDateLabel: 'ven. 26 juin',
    checkinDateLabel: 'jeu. 25 juin',
    nights: 1,
    guests: 2,
    agency: 'Axel',
    status: 'todo',
    cleaningAgent: 'Axel',
    startTime: '',
    endTime: '',
    linens: ['Draps queen x1'],
    consumables: ['Capsules café x4'],
    comments: '',
    problems: [],
    isSameDayCheckin: true,
    assignedVia: 'auto',
  },
  {
    id: 4,
    property: 'La Monnaie',
    displayId: '#20',
    address: "1 Rue de l'Ancienne Préfecture, 69002, Lyon",
    checkoutTime: '10:00',
    checkinTime: '17:00',
    checkoutDateLabel: 'ven. 26 juin',
    checkinDateLabel: 'ven. 29 mai',
    nights: 28,
    guests: 4,
    agency: 'Sihem',
    status: 'todo',
    cleaningAgent: 'Sihem',
    startTime: '',
    endTime: '',
    linens: ['Draps king size x2'],
    consumables: ['Capsules café x6'],
    comments: '',
    problems: [],
    isSameDayCheckin: true,
    assignedVia: 'auto',
  },
  {
    id: 5,
    property: 'Le Stendhal',
    displayId: '#03',
    address: '12 Rue Stendhal, 69002, Lyon',
    checkoutTime: '10:00',
    checkinTime: '16:00',
    checkoutDateLabel: 'ven. 26 juin',
    checkinDateLabel: 'lun. 22 juin',
    nights: 4,
    guests: 3,
    agency: 'Sihem',
    status: 'inProgress',
    cleaningAgent: 'Cleaning Agent',
    startTime: '10:30',
    endTime: '',
    linens: ['Draps simple x1'],
    consumables: ['Capsules café x2'],
    comments: '',
    problems: [],
    isSameDayCheckin: true,
    assignedVia: 'auto',
  },
  {
    id: 6,
    property: 'Hamac Suites - Lafayette',
    displayId: '#11',
    address: '23 Rue Lafayette, 69006, Lyon',
    checkoutTime: '11:00',
    checkinTime: '15:00',
    checkoutDateLabel: 'ven. 26 juin',
    checkinDateLabel: 'mar. 23 juin',
    nights: 3,
    guests: 2,
    agency: 'Amel',
    status: 'todo',
    cleaningAgent: 'Amel',
    startTime: '',
    endTime: '',
    linens: ['Draps queen x1'],
    consumables: ['Capsules café x4'],
    comments: '',
    problems: [],
    assignedVia: 'auto',
  },
  {
    id: 8,
    property: 'Maison 23 Rue de la Paix',
    displayId: '#08',
    address: '23 Rue de la Paix, 69007, Lyon',
    checkoutTime: '09:00',
    checkinTime: '14:00',
    checkoutDateLabel: 'ven. 26 juin',
    checkinDateLabel: 'mer. 24 juin',
    nights: 2,
    guests: 4,
    agency: 'Axel',
    status: 'completed',
    cleaningAgent: 'Cleaning Agent',
    startTime: '09:15',
    endTime: '11:30',
    linens: ['Draps king size x2'],
    consumables: ['Capsules café x6'],
    comments: '',
    problems: [],
    assignedVia: 'manual',
    lastAssignmentActor: 'Camille (manager)',
    photos: [
      { id: 'p1', url: photoSalon, caption: 'Salon', timestamp: '2026-06-26T11:23:00', agent: 'Sophie Renard' },
      { id: 'p2', url: photoCuisine, caption: 'Cuisine', timestamp: '2026-06-26T11:31:00', agent: 'Sophie Renard' },
      { id: 'p3', url: photoChambre, caption: 'Chambre principale', timestamp: '2026-06-26T11:45:00', agent: 'Sophie Renard' },
      { id: 'p4', url: photoSdb, caption: 'Salle de bain', timestamp: '2026-06-26T11:52:00', agent: 'Sophie Renard' },
      { id: 'p5', url: photoEntree, caption: 'Entrée', timestamp: '2026-06-26T12:01:00', agent: 'Sophie Renard' },
    ],
  },
];

export const initialTomorrowTasks: CleaningTask[] = [
  {
    id: 41,
    property: 'Appartement 45 Boulevard Central',
    displayId: '#45',
    address: '45 Bd Central, 69003, Lyon',
    checkoutTime: '11:00',
    checkinTime: '15:00',
    checkoutDateLabel: 'sam. 27 juin',
    checkinDateLabel: 'mer. 24 juin',
    nights: 3,
    guests: 2,
    agency: 'Marie',
    status: 'scheduled',
    cleaningAgent: 'Marie Lambert',
    startTime: '',
    endTime: '',
    linens: ['Draps queen x1'],
    consumables: ['Capsules café x4'],
    comments: '',
    problems: [],
  },
  {
    id: 51,
    property: 'Studio 15 Rue des Lilas',
    displayId: '#15',
    address: '15 Rue des Lilas, 69004, Lyon',
    checkoutTime: '10:00',
    checkinTime: '14:00',
    checkoutDateLabel: 'sam. 27 juin',
    checkinDateLabel: 'jeu. 25 juin',
    nights: 2,
    guests: 1,
    status: 'scheduled',
    cleaningAgent: null,
    startTime: '',
    endTime: '',
    linens: ['Draps simple x1'],
    consumables: ['Capsules café x2'],
    comments: '',
    problems: [],
  },
];

export const initialCompletedTasks: CleaningTask[] = [
  {
    id: 61,
    property: 'Studio 15 Rue des Lilas',
    displayId: '#15',
    address: '15 Rue des Lilas, 69004, Lyon',
    date: '2026-06-25',
    status: 'completed',
    cleaningAgent: 'Lucas Martin',
    agency: 'Sihem',
    nights: 2,
    guests: 2,
    startTime: '10:30',
    endTime: '11:45',
    linens: ['Draps simple x1'],
    consumables: ['Capsules café x2'],
    comments: '',
    problems: [],
    photos: [
      { id: 'p6', url: photoChambre2, caption: 'Chambre', timestamp: '2026-06-25T11:20:00', agent: 'Lucas Martin' },
      { id: 'p7', url: photoSdb2, caption: 'Salle de bain', timestamp: '2026-06-25T11:28:00', agent: 'Lucas Martin' },
      { id: 'p8', url: photoCuisine2, caption: 'Cuisine', timestamp: '2026-06-25T11:35:00', agent: 'Lucas Martin' },
      { id: 'p9', url: photoEntree, caption: 'Entrée', timestamp: '2026-06-25T11:40:00', agent: 'Lucas Martin' },
    ],
  },
  {
    id: 71,
    property: 'Appartement 28 Avenue Victor Hugo',
    displayId: '#28',
    address: '28 Av. Victor Hugo, 69002, Lyon',
    date: '2026-06-25',
    status: 'completed',
    cleaningAgent: 'Cleaning Agent',
    agency: 'Amel',
    nights: 3,
    guests: 2,
    startTime: '13:00',
    endTime: '14:30',
    linens: ['Draps queen x1'],
    consumables: ['Capsules café x4'],
    comments: '',
    problems: [],
    photos: [
      { id: 'p10', url: photoSalon, caption: 'Salon', timestamp: '2026-06-25T14:05:00', agent: 'Marie Lambert' },
      { id: 'p11', url: photoChambre, caption: 'Chambre', timestamp: '2026-06-25T14:12:00', agent: 'Marie Lambert' },
      { id: 'p12', url: photoSdb, caption: 'Salle de bain', timestamp: '2026-06-25T14:18:00', agent: 'Marie Lambert' },
    ],
  },
];

// Initial new task template
export const initialNewTask: NewCleaningTask = {
  property: '',
  checkoutTime: '11:00',
  checkinTime: '15:00',
  status: 'todo',
  cleaningAgent: '',
  date: format(new Date(), 'yyyy-MM-dd'),
  linens: ['Serviettes bain x2', 'Serviettes main x2', 'Housse de couette queen x1', 'Taies d\'oreiller x2'],
  consumables: ['Capsules café x4', 'Sachets thé x2'],
  comments: '',
};
